# Generated by Django 5.2.5 on 2025-09-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample',
            new_name='User',
        ),
    ]
